#!/usr/bin/env bash

for o in c p u '-normal' e n y
do
	cat - <<-HEADER

	================================
	Testing diff files: diff -$o ...

	HEADER

	./colordiff tests/dir1/test-file-2 tests/dir2/test-file-2 -r -$o
done
